# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b58f007df34191ee2f25cef66dd7436ea60e562db7e5eded8fbbd6d6a96931a3bf58ba40c10b25180d3e4318a654014dc1b50cd2a689727e38bcdc2918462c06

test:
  secret_key_base: 067044679239d9a0b298a4cecb8120caf4cbe13e0124d48e06f7daf81bb43819f4c0478056ac659dc1dd51b710775c41d7380409680dae2621f304e4705786bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
